server:
  port: 8088
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
multitenancy:
  master:
    datasource:
      url: jdbc:postgresql://${POSTGRES_HOST}:5432/rhplus
      username: rhplus
      password: ${RHPLUS_PASSWORD}
    liquibase:
      changeLog: classpath:db/changelog/db.changelog-master.yaml
  tenant:
    datasource:
      url-prefix: jdbc:postgresql://${POSTGRES_HOST}:5432/
    liquibase:
      changeLog: classpath:db/changelog/db.changelog-tenant.yaml
encryption:
  secret: verySecret
  salt: jozo